# Generated by Django 4.1.4 on 2022-12-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_options_review_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
